### ISSUE TITLE
Get better name?

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#30]
Can we get a better name for the app than its RDNN? `Installing “org.gnome.Epiphany.Devel”` is accurate, but pretty ugly. :stuck_out_tongue:

**Comment by davidmhewitt** [comment]
So, a `.flatpakref` file can have a `Title` field that according to the spec "should be a user-friendly name that can be displayed e.g. in an app store".

We're currently using the `Name` field from the file which is just the RDNN, but the `Title` field in ref files from Flathub is `{RDNN} from flathub` due to how those files are generated by `flat-manager` for Flathub. I've raised an issue [here](https://github.com/flatpak/flat-manager/issues/24) but in the mean time I'll look at whether it's possible to download the appdata for a single app from the remote and get the name out of there.

**Comment by cassidyjames** [comment]
@davidmhewitt it looks like GNOME Software is doing something smart, because opening a `.flatpakref` file there seems to get the right metadata. Unless that's because it already had it from the remote? I'll need to remove all remotes and test some more.

**Comment by davidmhewitt** [comment]
Looking at the GNOME Software code, it looks like they're adding the remote and pulling the appdata to get the metadata about the app. This wouldn't be necessary for us if the `Title` field in the `.flatpakref` files was right, but I guess it gives us the opportunity to get extra metadata if we need it.
